Repository koor-tech/koor, pull requests merged in 2022-11, with the labels that each got.

#14 core: add office hours meeting to readme
  README.md
Labels: documentation, skip-ci

#15 design: added ceph dashboard sso design doc
  design/ceph/ceph-dashboard-sso.md
Labels: documentation, enhancement, skip-ci

#13 core: remove manual renaming and let script handle rook to koor renaming
  rook-to-koor.sh
Labels: skip-ci
